import type { ActionItem, Channel, Meeting, Person } from './types'

export const seedChannels: Channel[] = [
  { id: 'general', name: 'General', slug: 'general' },
  { id: 'client-calls', name: 'Client Calls', slug: 'client-calls' },
  { id: 'internal-syncs', name: 'Internal Syncs', slug: 'internal-syncs' },
  { id: 'project-updates', name: 'Project Updates', slug: 'project-updates' },
  { id: 'operations', name: 'Operations', slug: 'operations' },
  { id: 'business-dev', name: 'Business Development', slug: 'business-dev' },
]

export const seedPeople: Person[] = [
  { id: 'p1', name: 'Garrick Lewis', role: 'Director of Operations', email: 'garrick.lewis@abonmarche.com' },
  { id: 'p2', name: 'Samantha Ortiz', role: 'Project Manager', email: 'samantha.ortiz@abonmarche.com' },
  { id: 'p3', name: 'Priya Desai', role: 'Civil Engineer', email: 'priya.desai@abonmarche.com' },
  { id: 'p4', name: 'Caleb Turner', role: 'Business Development', email: 'caleb.turner@abonmarche.com' },
  { id: 'p5', name: 'Liam Chen', role: 'Field Supervisor', email: 'liam.chen@abonmarche.com' },
]

const now = new Date()

const dateString = (offsetDays: number) => {
  const d = new Date(now)
  d.setDate(d.getDate() - offsetDays)
  return d.toISOString()
}

export const seedMeetings: Meeting[] = [
  {
    id: 'm1',
    title: 'Springfield Pipeline Inspection Kickoff',
    date: dateString(2),
    channelId: 'client-calls',
    type: 'client',
    participants: ['p1', 'p3', 'p5'],
    transcript: 'Discussed scope for Springfield pipeline inspection. Agreed on phased CCTV schedule and MACP reporting cadence.',
    summary: 'Confirmed phased CCTV inspection schedule, MACP reporting cadence, and client checkpoints.',
    keyDecisions: [
      'CCTV inspections to run in three phases with weekly checkpoints',
      'MACP reports delivered every Friday at 4pm ET',
      'Client to provide as-builts before phase 2',
    ],
    topics: ['CCTV', 'MACP', 'schedule'],
    sentiment: 'productive',
    actionItemIds: ['a1', 'a2'],
    followUpDraft: 'Thanks for meeting. Attached is the agreed inspection cadence and MACP delivery schedule. We will send the phase 1 kickoff materials by Wednesday.',
    insights: ['Client is sensitive to schedule risk; emphasize weekly check-ins'],
    riskFlags: ['As-builts dependency'],
    relatedMeetingIds: [],
    createdAt: dateString(2),
    updatedAt: dateString(2),
  },
  {
    id: 'm2',
    title: 'Weekly Operations Standup',
    date: dateString(1),
    channelId: 'internal-syncs',
    type: 'internal',
    participants: ['p1', 'p2', 'p3', 'p5'],
    transcript: 'Reviewed crew allocation, equipment status, and weather risks. Flagged backlog in report reviews.',
    summary: 'Crew allocation adjusted for weather, backlog of report reviews assigned, equipment maintenance scheduled.',
    keyDecisions: ['Move crew Bravo to Site 4', 'Schedule vac truck maintenance Thursday', 'Triage report backlog by Friday'],
    topics: ['resourcing', 'weather', 'reports'],
    sentiment: 'productive',
    actionItemIds: ['a3', 'a4'],
    followUpDraft: 'Here is the follow-up: crew moves, maintenance window, and report backlog owners. Please update status by Thursday EOD.',
    insights: ['Report backlog is recurring; may need automation for QC checks'],
    riskFlags: ['Weather risk this week'],
    relatedMeetingIds: ['m1'],
    createdAt: dateString(1),
    updatedAt: dateString(1),
  },
  {
    id: 'm3',
    title: 'Q1 Planning with Garrick',
    date: dateString(7),
    channelId: 'general',
    type: 'one-on-one',
    participants: ['p1', 'p4'],
    transcript: 'Reviewed Q1 targets, BD pipeline, and training priorities for inspectors.',
    summary: 'Set Q1 targets, prioritized BD pursuits, and aligned on inspector training curriculum.',
    keyDecisions: ['Focus BD on municipal renewals', 'Launch inspector training module by Feb 15'],
    topics: ['BD pipeline', 'training', 'targets'],
    sentiment: 'neutral',
    actionItemIds: ['a5'],
    followUpDraft: 'Recap: Q1 targets locked, BD focus on municipal renewals, training module by Feb 15. Next check-in in two weeks.',
    insights: ['Training investment linked to report quality improvements'],
    riskFlags: [],
    relatedMeetingIds: [],
    createdAt: dateString(7),
    updatedAt: dateString(7),
  },
  {
    id: 'm4',
    title: 'NASSCO Certification Review',
    date: dateString(10),
    channelId: 'project-updates',
    type: 'project',
    participants: ['p2', 'p3', 'p5'],
    transcript: 'Covered NASSCO certification gaps and remediation plan for inspectors.',
    summary: 'Identified certification gaps; set remediation steps and deadlines.',
    keyDecisions: ['Enroll two inspectors in refresher course', 'Audit five recent reports for compliance'],
    topics: ['NASSCO', 'compliance', 'training'],
    sentiment: 'productive',
    actionItemIds: ['a6'],
    followUpDraft: 'Attached remediation plan and audit checklist. Please confirm enrollments by Friday.',
    insights: ['Certification gaps tied to turnover; consider quarterly refreshers'],
    riskFlags: ['Compliance exposure if audits slip'],
    relatedMeetingIds: [],
    createdAt: dateString(10),
    updatedAt: dateString(10),
  },
]

export const seedActionItems: ActionItem[] = [
  {
    id: 'a1',
    meetingId: 'm1',
    task: 'Send MACP phase 1 kickoff packet to client',
    ownerId: 'p3',
    status: 'todo',
    due: dateString(1),
    order: 1,
  },
  {
    id: 'a2',
    meetingId: 'm1',
    task: 'Request as-builts from client for phase 2',
    ownerId: 'p1',
    status: 'in_progress',
    due: dateString(3),
    order: 2,
  },
  {
    id: 'a3',
    meetingId: 'm2',
    task: 'Reassign crew Bravo to Site 4 for weather window',
    ownerId: 'p5',
    status: 'todo',
    due: dateString(0),
    order: 1,
  },
  {
    id: 'a4',
    meetingId: 'm2',
    task: 'Clear report review backlog by Friday',
    ownerId: 'p2',
    status: 'in_progress',
    due: dateString(1),
    order: 2,
  },
  {
    id: 'a5',
    meetingId: 'm3',
    task: 'Finalize Q1 BD target list and share to ops',
    ownerId: 'p4',
    status: 'done',
    due: dateString(5),
    order: 1,
  },
  {
    id: 'a6',
    meetingId: 'm4',
    task: 'Enroll inspectors in NASSCO refresher course',
    ownerId: 'p2',
    status: 'todo',
    due: dateString(6),
    order: 1,
  },
]
